version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: harmonyvault
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'